version: '3.7'
services:
  nestjs-service:
    image: abeesdevjs/gateway-service:${TAG}
    deploy:
      mode: global
    ports:
      - '8080:8080'
    environment:
      - CONFIG_PORT=8080
      - CONFIG_NESTJS_SERVICE=http://18.140.61.152:8080
